name: Deploy to Lambda

on:
  push:
    branches:
      - master
jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [20.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies, build application and zip folder contents
        run: npm install && npm run build && cp -r ./node_modules dist && cd dist && zip -qq -r ./james_bot.zip . && mv james_bot.zip ..
      - name: Main Deploy AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: james_reminder_bot
          zip_file: james_bot.zip
      - name: Birthday Reminder Deploy AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: james_birthday_check
          zip_file: james_bot.zip
      - name: Garbage Date Deploy AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: james_garbage_check
          zip_file: james_bot.zip
